### ISSUE TITLE
spelling error

### ISSUE THREAD

**Issue by ohyayo** [vorja/SleekDBVCMS#1]
Exmaple Index Page -=> Example Index Page

**Comment by borjajimnz** [comment]
Hello and thanks, soon Ill update the project to make It work with the last version of SleekDB.

**Comment by ohyayo** [comment]
Yeah, no problem.  Hey, this is the first time I've gotten involved in a project here on Git.

I started by downloading SleekDB and following their installation process... I got this project 2nd.  I believe that there needs to be a field in the config to specify where the DB Directory should be.  I haven't gotten too much further in yet, as I was wondering if maybe you already had some updates you were working on.

For instance, this is what I have in my test.php file, based on SleekDB setup:

<?php
require_once ($public_DIR . "/DBfiles/SleekDB/Store.php");

// dir name to store Database files/directories
$databaseDirectory = ($public_DIR . "/DBfiles");  

//initialize the store.
//If the store doesn't exist it will be created automatically.

$newsStore = new \SleekDB\Store("news", $databaseDirectory);
?>

Also, I'm not sure if it would work, but would it be advisable to keep the database in the directory level before /public ??

Like:  /var/www/MySite/DBfiles

instead of:
/var/www/MySite/public/SleekDB/

Anyway, great idea for a project... I'll try to help as time goes on.

**Comment by ohyayo** [comment]
test.php:

require_once ($Public_Dir . "/DBfiles/sleekdb/Store.php"); 

$databaseDirectory = ($Public_Dir . "/DBfiles");  // dir name for SleekDB database .json files

//initialize the store.
//If the store doesn't exist it will be created automatically.

$newsStore = new \SleekDB\Store("news", $databaseDirectory);
